# Generated by Django 4.1.1 on 2022-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Author', models.TextField()),
                ('Genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Literary', 'Literary'), ('Mystery', 'Mystery'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller')], max_length=15)),
                ('Review', models.IntegerField()),
                ('Favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
